### PR TITLE
Adding check for local dynamo status on app startup

### PR DESCRIPTION
**Pull request by nmonga91**
@bsweger or @jworcestBAH

### CODE REVIEW

**Comment by bsweger** [comment]
@nmonga91 This is working as expected on OSX (i.e, it produces error messages when local dynamo isn't running). @jworcestBAH can you confirm that this works on Windows?

The only flag here is that at least on OSX, the nmap install gets an unsigned warning. If someone asks, where can we point them to ensure that this is a safe app to use?

**Comment by jworcestBAH** [comment]
So this does not work on windows after installing nmap because awk is not a command in windows.  One fix could be to add a utility that can replace that to install instructions and have a conditional that runs a different command here for windows.

**Comment by jworcestBAH** [comment]
Alternatively, can we rewrite this to not use awk?

**Comment by bsweger** [comment]
@jworcestBAH thanks for testing this on Windows! What do you and @nmonga91 think about making this simpler and trying to issue a dummy session table request to Dynamo and forcing an error if said request doesn't return in n amount of time? Not as precise but would limit the extra installs and cross-platform issues.

**Comment by jworcestBAH** [comment]
I would be happy with that solution, not requiring users to install extra things is a nice benefit.

**Comment by bsweger** [comment]
Thanks for weighing in. I should have been explicit and said that I like @nmonga91's timing and the approach of doing the check when the app starts up.

**Pull request closed without merging**
